version: '2.1'

volumes:
  settings:

services:
  browser:
    image: balenablocks/browser:raspberrypi3
    privileged: true
    network_mode: host
    volumes:
      - 'settings:/data'
    environment:
      ENABLE_GPU: 1
      DEBUG: 1
      KIOSK: 1
      SHOW_CURSOR: 0
      LOCAL_HTTP_DELAY: 5

  server:
    restart: always
    build: ./services/server
    ports:
      - 80:3000

  wifi-connect:
    build: ./services/wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
